use std::env;
use std::path::PathBuf;

fn main() {
    // Only generate C headers for iOS builds
    let target = env::var("TARGET").unwrap_or_default();
    let is_ios = target.contains("apple-ios") || target.contains("aarch64-apple-darwin");

    // Also check for the ios feature
    let has_ios_feature = env::var("CARGO_FEATURE_IOS").is_ok();

    if is_ios || has_ios_feature {
        let crate_dir = env::var("CARGO_MANIFEST_DIR").unwrap();
        let out_dir = PathBuf::from(&crate_dir).join("include");

        // Create include directory if it doesn't exist
        std::fs::create_dir_all(&out_dir).ok();

        let config = cbindgen::Config {
            language: cbindgen::Language::C,
            cpp_compat: true,
            include_guard: Some("GB_EMU_H".to_string()),
            pragma_once: false,
            autogen_warning: Some(
                "// Auto-generated by cbindgen. Do not edit manually.".to_string()
            ),
            ..Default::default()
        };

        cbindgen::Builder::new()
            .with_crate(&crate_dir)
            .with_config(config)
            .generate()
            .expect("Unable to generate C bindings")
            .write_to_file(out_dir.join("gb_emu.h"));

        println!("cargo:rerun-if-changed=src/ffi.rs");
    }
}
