#ifndef GB_EMU_H
#define GB_EMU_H

// Auto-generated by cbindgen. Do not edit manually.

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

#define BUTTON_A 0

#define BUTTON_B 1

#define BUTTON_SELECT 2

#define BUTTON_START 3

#define BUTTON_RIGHT 4

#define BUTTON_LEFT 5

#define BUTTON_UP 6

#define BUTTON_DOWN 7

#define GB_BUTTON_A 0

#define GB_BUTTON_B 1

#define GB_BUTTON_SELECT 2

#define GB_BUTTON_START 3

#define GB_BUTTON_RIGHT 4

#define GB_BUTTON_LEFT 5

#define GB_BUTTON_UP 6

#define GB_BUTTON_DOWN 7

#define GB_SCREEN_WIDTH 160

#define GB_SCREEN_HEIGHT 144

#define GB_CAMERA_WIDTH 128

#define GB_CAMERA_HEIGHT 112

#endif  /* GB_EMU_H */
